steps:
- name: 'gcr.io/cloud-builders/curl'
  args: ['-XPUT', '-d', '{ "repoName": "$REPO_NAME", "status": "RUNNING", "commitSha": "$COMMIT_SHA", "buildId": "$BUILD_ID", "testResults": "{}"}', 'https://hnvbmypjh9.execute-api.eu-central-1.amazonaws.com/prod/builds']
- name: 'gcr.io/cloud-builders/npm'
  args: ['ci']
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'test-silent']
- name: 'gcr.io/eloquent-hour-220409/test-results-reporter'
  args: ['https://hnvbmypjh9.execute-api.eu-central-1.amazonaws.com/prod/builds', './test-results.json']  
  env:
    - 'BUILD=$BUILD_ID'
    - 'REPO=$REPO_NAME'
    - 'COMMIT_SHA=$COMMIT_SHA'
    